### ISSUE TITLE
Not open-source

### ISSUE THREAD

**Issue by serbinskis** [WooxHimself/neverwhere#5]
This shit is sketchy as fuck. Your dll (executor) is not open-source.

**Comment by nwvh** [comment]
What the fuck are you talking about. First of all, this shit is unmaintained, so I don't know why you're creating an issue on dead project. Second of all, there's not a single .dll file in both the executor itself or the API so your issue is pointless.

**Comment by serbinskis** [comment]
🤡🤡🤡
![image](https://github.com/nwvh/neverwhere/assets/66483092/e06e2bd3-c9ff-4e1b-8be1-d6f874a43f67)

**Comment by nwvh** [comment]
> 🤡🤡🤡
> ![image](https://github.com/nwvh/neverwhere/assets/66483092/e06e2bd3-c9ff-4e1b-8be1-d6f874a43f67)
> 

You're so fucking retarded, you have to compile the dll yourself and then add it to the project. fucking retard you're so fucking dumb.

**Comment by serbinskis** [comment]
The only retard here is you. Don't upload such shit to github and call it open-source if you can't even make dll public.

**Comment by blahblu2** [comment]
mf using easyxploits script 😭😭

**Comment by nwvh** [comment]
> mf using easyxploits script 😭😭

retarded mf commenting 3 year old unmaintained project
